export const CONSTANTS: any = {
  TEMP_JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
  JWT_TOKEN: 'JWT_TOKEN',
  EMP_DASHBOARD: 'emp-dashboard',
  ADMIN_DASHBOARD: 'admin-dashboard',
  HR_DASHBOARD: 'hr-dashboard',
  LOGIN: 'login',
  LOGOUT: 'logout',
  ON_DUTY: 'on_duty',
  WORK_FROM_HOME: 'work_from_home',
  WEB_CHECK_IN: 'web_check_in',
  REMOTE: 'remote',
  EMPTY: '',
  FULL: 'full',
  PREFIX: 'prefix',
  REFRESH: 'refresh',
  MY_PROFILE: 'my-profile',
  CREATE_POST: 'create-post',
  CREATE_PROFILE: 'create-profile',
  EMP_ATTENDANCE: 'emp-attendance',
  EMP_ATTENDANCE_DETAILS: 'emp-attendance-details',
  EMP_FINANCES: 'emp-finances',
  EMP_FINANCES_DETAILS: 'emp-finances-details',
  EMP_LEAVES: 'emp-leaves',
  EMP_LEAVES_DETAILS: 'emp-leaves-details',
  EMP_EXPENSE_CLAIM: 'emp-expense-claim',
  EMP_EXPENSE_CLAIM_DETAILS: 'emp-expense-claim-details',
  EMP_GOALS_PERFORMANCE: 'emp-goals-performance',
  EMP_GOALS_PERFORMANCE_DETAILS: 'emp-goals-performance-details',
  EMP_MY_ORG: 'emp-my-org',
  DASHBOARD_ALL: 'dashboard-all',
  ADMIN_ALL_EMPLOYEES: 'admin-all-employees',
  ADMIN_DEPARTMENTS: 'admin-departments',
  ADMIN_DESIGNATIONS: 'admin-designations',
  ADMIN_SHIFTS: 'admin-shifts',
  ADMIN_ROLES: 'admin-roles',
  ADMIN_DUTY_ROSTER: 'admin-duty-roster',
  ADMIN_HOLIDAYS: 'admin-holidays',
  ADMIN_TIMESHEET: 'admin-timesheet',
  ADMIN_USERS: 'admin-users',
  ADMIN_COMPANIES: 'admin-companies',
  ADMIN_ACTIVITY_LOGS: 'admin-activity-logs',
  ADMIN_SETTINGS: 'admin-settings',
  ADMIN_ATTENDANCE: 'admin-attendance',
  ADMIN_ATTENDANCE_DETAILS: 'admin-attendance-details',
  ADMIN_FINANCES: 'admin-finances',
  ADMIN_FINANCES_DETAILS: 'admin-finances-details',
  ADMIN_LEAVES: 'admin-leaves',
  ADMIN_LEAVES_DETAILS: 'admin-leaves-details',
  ADMIN_EXPENSE_CLAIM: 'admin-expense-claim',
  ADMIN_EXPENSE_CLAIM_DETAILS: 'admin-expense-claim-details',
  ADMIN_JOBS: 'admin-jobs',
  ADMIN_JOBS_DASHBOARD: 'admin-jobs-dashboard',
  ADMIN_JOBS_DASHBOARD_DETAILS: 'admin-jobs-dashboard-details',
  ADMIN_CANDIDATES_DASHBOARD: 'admin-candidates-dashboard',
  ADMIN_CANDIDATES_DASHBOARD_DETAILS: 'admin-candidates-dashboard-details',
  ADMIN_GOALS_PERFORMANCE: 'admin-goals-performance',
  ADMIN_GOALS_PERFORMANCE_DETAILS: 'admin-goals-performance-details',
  ADMIN_SALARY_PATH: 'salary',
  ADMIN_SALARY_LABEL: 'Salary Master',
  ADMIN_SHIFT_PATH: 'shift',
  ADMIN_SHIFT_LABEL: 'Shift Schedule',
  ADMIN_GENERAL_PATH: 'general',
  ADMIN_GENERAL_LABEL: 'General',
  ADMIN_COMPANY_PATH: 'company',
  ADMIN_COMPANY_LABEL: 'Company',
  ADMIN_FINANCE_PATH: 'finances',
  ADMIN_FINANCE_LABEL: 'Finances',
  ADMIN_SYSTEM_PATH: 'system',
  ADMIN_SYSTEM_LABEL: 'System',
  ADMIN_OTHER_MASTERS_PATH: 'other-masters',
  ADMIN_OTHER_MASTERS_LABEL: 'Other Masters',
  ADMIN_MASTERS_PATH: 'masters',
  ADMIN_MASTERS_LABEL: 'Masters',
  ADMIN_APPROVAL_PATH: 'approval',
  ADMIN_APPROVAL_LABEL: 'Approval',
  ADMIN_PERFORMANCE_PATH: 'performance',
  ADMIN_PERFORMANCE_LABEL: 'Performance',
  ADMIN_LEAVE_PATH: 'leave',
  ADMIN_LEAVE_LABEL: 'Leave',
  ADMIN_ROLES_PRIVILEGES_PATH: 'roles-privileges',
  ADMIN_ROLES_PRIVILEGES_LABEL: 'Roles & Privileges',
  ADMIN_CRON_JOB_PATH: 'cron-jobs',
  ADMIN_CRON_JOB_LABEL: 'Cron Jobs',
  CHECK_CIRCLE: 'check_circle',
  APPROVE: 'approve',
  REJECT: 'reject',
  ADD: 'add',
  EDIT: 'edit',
  VISIBILITY: 'visibility',
  READ_ONLY: 'readonly',
  CANCEL: 'cancel',
  ADD_ANY: 'add_any',
  SEARCH: 'search',
  FILTER_SEARCH: 'filter_search',
  FILTER_SWAP_DUTY: 'filter_swap_duty',
  UPLOAD_ANY: 'upload_any',
  UPDATE: 'update',
  BULK_UPLOAD: 'bulk upload',
  ADD_EMPLOYEE: 'add_employee',
  REQUEST: 'request',
  REQUEST_LEAVE: 'request_leave',
  REQUEST_CLAIM: 'request_claim',
  REQUEST_LOAN: 'request_loan',
  REQUEST_ATTENDANCE: 'request_attendance',
  VIEW_ALL: 'view_All',
  GRID_ADD_ROW: 'grid_add_row',
  GRID_REMOVE_ROW: 'grid_remove_row',
  REQUEST_CORRECTION: 'request_correction',
  CHECKBOX_CHANGED: 'checkbox_changed',
  IHRMS_GRID_COMPONENT: 'IhrmsGridComponent',
  IHRMS_LIST_ITEMS_COMPONENT: 'IhrmsListItemsComponent',
  IHRMS_WEBDATAROCKS_COMPONENT: 'IhrmsWebDataRocks',
  IHRMS_CHART_COMPONENT: 'IhrmsChartComponent',
  IHRMS_FILTERS_COMPONENT: 'IhrmsFiltersComponent',
  IHRMS_MULTI_CHART_COMPONENT: 'MultiChartsComponent',
  ROW_CLICKED: 'row_clicked',
  ROW_DOUBLE_CLICKED: 'row_double_clicked',
  ON_CELL_VALUE_CHANGED: 'onCellValueChanged',
  ON_SELECTION_CHANGED: 'onSelectionChanged',
  ON_FIRST_DATA_RENDERED: 'onFirstDataRendered',
  ON_ROW_SELECTED: 'onRowSelected',
  ON_GRID_READY: 'onGridReady',
  FORM_OBJECT_EVENT: 'formObjectEvent',
  FORM_SUBMIT_EVENT: 'formSubmitEvent',
  FORM_STATUS_CHANGE: 'statusChanges',
  FORM_VALUE_CHANGE: 'valueChanges',
  SUCCESS: 'Success',
  ERROR: 'Error',
  VALIDATION_ERROR: 'Validation Error',
  TITLES: {
    Overview: 'Overview',
    AttendanceType: 'Attendance Type',
    AttendanceCorrections: 'Attendance Corrections',
    AttendanceTimeCorrections: 'Attendance Time Corrections',
    AttendanceRequests: 'Attendance Requests',
    AttendanceTypeRequests: 'Attendance Type Requests',
    TodaysAttendance: 'Today\'s Attendance',
    TimesheetCorrections: 'Timesheet Corrections',
    RequestsApprovals: 'Requests Approvals',
    PayrollInputs: 'Payroll Inputs',
    RequestsApprovalsClaims: 'Requests Approvals Claims',
    RequestsApprovalsLoans: 'Requests Approvals Loans',
    RecentAttendance: 'Recent Attendance',
    MyRequests: 'My Requests',
    PayrollHistoric: 'Payroll Historic',
    Salary: 'Salary',
    SalaryRevisions: 'Salary Revisions',
    MyClaims: 'My Claims',
    MyLoans: 'My Loans',
    Attendance: 'Attendance',
    Attendances: 'Attendances',
    AddAttendance: 'Add Attendance',
    EditAttendance: 'Edit Attendance',
    DeleteAttendance: 'Delete Attendance',
    Employee: 'Employee',
    Employees: 'Employees',
    AddEmployee: 'Add Employee',
    EditEmployee: 'Edit Employee',
    DeleteEmployee: 'Delete Employee',
    Department: 'Department',
    Departments: 'Departments',
    AddDepartment: 'Add Department',
    EditDepartment: 'Edit Department',
    DeleteDepartment: 'Delete Department',
    Designation: 'Designation',
    Designations: 'Designations',
    AddDesignation: 'Add Designation',
    EditDesignation: 'Edit Designation',
    DeleteDesignation: 'Delete Designation',
    Shift: 'Shift',
    Shifts: 'Shifts',
    AddShift: 'Add Shift',
    EditShift: 'Edit Shift',
    DeleteShift: 'Delete Shift',
    Role: 'Role',
    Roles: 'Roles',
    AddRole: 'Add Role',
    EditRole: 'Edit Role',
    DeleteRole: 'Delete Role',
    Holiday: 'Holiday',
    Holidays: 'Holidays',
    AddHoliday: 'Add Holiday',
    EditHoliday: 'Edit Holiday',
    DeleteHoliday: 'Delete Holiday',
    Leave: 'Leave',
    LeaveType: 'LeaveType',
    LeaveTypes: 'LeaveTypes',
    AddLeaveType: 'Add LeaveType',
    EditLeaveType: 'Edit LeaveType',
    DeleteLeaveType: 'Delete LeaveType',
    Timesheet: 'Timesheet',
    AddTimesheet: 'Add Timesheet',
    EditTimesheet: 'Edit Timesheet',
    DeleteTimesheet: 'Delete Timesheet',
    User: 'User',
    Users: 'Users',
    AddUser: 'Add User',
    EditUser: 'Edit User',
    DeleteUser: 'Delete User',
    Tenant: 'Tenant',
    Company: 'Company',
    Companies: 'Companies',
    AddCompany: 'Add Company',
    EditCompany: 'Edit Company',
    DeleteCompany: 'Delete Company',
    DutyRoster: 'Duty Roster',
    DutyRosters: 'Duty Rosters',
    AddDutyRoster: 'Add Duty Roster',
    EditDutyRoster: 'Edit Duty Roster',
    DeleteDutyRoster: 'Delete Duty Roster',
    AttendanceRequest: 'AttendanceRequest',
    Jobs: 'Jobs',
    LatestJobs: 'Latest Jobs',
    OfferedJobs: 'Offered Jobs',
    AppliedJobs: 'Applied Jobs',
    CandidatesOverview: 'Candidates Overview',
    JobsOverview: 'Jobs Overview',
    Candidates: 'Candidates',
    ApplicantsList: 'Applicants List',
    ShortlistCandidates: 'Shortlist Candidates',
    EmployeeType: 'EmployeeType',
    AddEmployeeType: 'Add EmployeeType',
    EditEmployeeType: 'Edit EmployeeType',
    DeleteEmployeeType: 'Delete EmployeeType',
    BloodGroup: 'BloodGroup',
    Cast: 'Cast',
    Country: 'Country',
    Gender: 'Gender',
    MaritalStatus: 'MaritalStatus',
    ModeOfEmployement: 'ModeOfEmployement',
    Relation: 'Relation',
    Status: 'Status',
    Title: 'Title',
    ShiftType: 'ShiftType',
    JobTitle: 'JobTitle',
    AuditLogs: 'Audit Logs',
    MyGoals: 'My Goals',
    AllGoals: 'All Goals',
    AllAssignedGoals: 'All Assigned Goals',
    Goals: 'Goals',
    KeyPerformanceEvents: 'Key Performance Events',
    GoalsAndDevelopments: 'Goals And Developments',
    FeedbackReceived: 'Feedback Received',
    AllFeedbacks: 'All Feedbacks',
    AllAssignedFeedbacks: 'All Assigned Feedbacks',
    Feedbacks: 'Feedbacks',
    MyFeedbacks: 'My Feedbacks',
    PerformanceDiscussion: 'Performance Discussion',
    PerformanceDiscussions: 'Performance Discussions',
    AllPerformanceDiscussions: 'All Performance Discussions',
    GetFeedback: 'GetFeed back',
  },
  ROLE: 'role',
  ADMIN: 'Admin',
  GONNGOD: 'GONNGOD',
  EVENTS: {
    pointClickEvent: 'pointClickEvent',
    seriesClickEvent: 'seriesClickEvent',
  },
  Pending: 'Pending',
  Approved: 'Approved',
  Rejected: 'Rejected',
  Recalled: 'Recalled',
}
